news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
  eltiempo:
    url: https://www.eltiempo.com
    queries:
      homepage_article_links: '.title-container a'