news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
      article_body: 'field-name-body'
      article_title: 'pane-content h1'
  eltiempo:
    url: https://www.eltiempo.com
    queries:
      homepage_article_links: '.title-container a'
      article_body: 'field-name-body'
      article_title: 'titulo-principal-bk h1'